name: Command

on:
  issue_comment: # listen for comments on issues
    types: [created]

permissions: # allow the action to comment on the PR
  contents: write
  issues: write
  pull-requests: write

jobs:
  cmd:
    if: startsWith(github.event.comment.body, '/cmd')
    runs-on: arc-runners-beefy-stg
    steps:
      - name: Install updates and protobuf-compiler
        run: |
          sudo apt update && sudo apt install --assume-yes \
            pkg-config g++ make cmake protobuf-compiler curl libssl-dev libclang-dev libudev-dev git

      - name: Generate a token
        id: commands_token
        uses: actions/create-github-app-token@v1.8.1
        with:
          app-id: ${{ secrets.COMMAND_APP_ID }}
          private-key: ${{ secrets.COMMAND_APP_KEY }}

      - name: Build workflow link
        id: build-link
        run: |
          workflowId=$(curl -s \
            -H "Authorization: token ${{ steps.commands_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq .workflow_id)
          
          echo "workflow_id=${workflowId}"

          workflowLink="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/workflow/${workflowId}"

          echo "workflow_link=${workflowLink}"
          echo "workflow_link=$workflowLink" >> $GITHUB_ENV

      - name: Comment PR (Start)
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.commands_token.outputs.token }}
          #        github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // get username of token
            const { data: { login: username } } = await github.rest.users.getAuthenticated()
            
            // clean previous comments
            github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            }).then(comments => {
              comments.data.forEach(comment => {
                if (comment.user.login === username) {
                  github.rest.issues.deleteComment({
                    comment_id: comment.id,
                    owner: context.repo.owner,
                    repo: context.repo.repo
                  })
                }
              })
            })
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Command "${{ steps.get-pr-comment.outputs.group2 }}" has started! Output: [Link to pipeline](${{ env.workflow_link }})`
            })

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set rust version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "wasm32-unknown-unknown"
          components: "rust-src rustfmt clippy"
          toolchain: "nightly-${{env.RUST_NIGHTLY_VERSION}}"

      - name: Get command
        uses: actions-ecosystem/action-regex-match@v2
        id: get-pr-comment
        with:
          text: ${{ github.event.comment.body }}
          regex: '^(\/cmd )(.*)$'

      - name: Install dependencies for bench
        if: startsWith(steps.get-pr-comment.outputs.group2, 'bench')
        run: cargo install subweight frame-omni-bencher

      - name: Setup Cache
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43 # v2.7.0
        with:
          shared-key: "fellowship-cmd"

      - name: Run cmd
        id: cmd
        env:
          CMD: ${{ steps.get-pr-comment.outputs.group2 }} # to avoid "" around the command
        run: |
          echo "Running command: $CMD"
          git remote -v
          python3 .github/scripts/cmd/cmd.py $CMD
          git status
          git diff

      - name: Comment PR (End)
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.commands_token.outputs.token }}
  #        github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Command "${{ steps.get-pr-comment.outputs.group2 }}" has finished! Output: [Link to pipeline](${{ env.workflow_link }})`
            })

      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            git pull origin ${{ github.head_ref }}
            git add .
            git commit -m "Update from ${{ github.actor }} running command '${{ steps.get-pr-comment.outputs.group2 }}'"
            git push origin ${{ github.head_ref }}
          else
            echo "Nothing to commit";
          fi
          
          
